trigger:
- master

pool: 'LinuxPool'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: |
     python -m venv antenv
     source antenv/bin/activate
     python -m pip install --upgrade pip
     pip install setup
     pip install -r requirements.txt
  displayName: "Install requirements"
- task: DownloadSecureFile@1
  inputs:
    secureFile: '.env'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Agent.TempDirectory)
    Contents: '**\.env'
    TargetFolder: $(Build.SourcesDirectory)  

- task: ArchiveFiles@2
  inputs:
     rootFolderOrFile: '$(Build.SourcesDirectory)'
     includeRootFolder: false
     archiveType: 'zip'
     archiveFile: '$(Build.ArtifactStagingDirectory)/Application.zip'
     replaceExistingArchive: true 



- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Application.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'