trigger:
- master

pool: 'LinuxPool'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: |
     python -m venv antenv
     source antenv/bin/activate
     python -m pip install --upgrade pip
     pip install setup
     pip install -r requirements.txt
  
- task: DownloadSecureFile@1
  inputs:
    secureFile: '.env'

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Agent.TempDirectory)
    Contents: '**\.env'
    TargetFolder: $(Build.SourcesDirectory)  

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'